package com.huaxin.test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.sql.Statement;

public class DbUtil {
								
	private static String url="jdbc:mysql://localhost:3306/travel?user=root&password=123456";
	private String username="root";
	private String password="123456";
	
	static{
		// driver=new com.mysql.jdbc.Dtalriver();
		try {
			Class.forName("com.mysql.jdbc.Driver");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	}
	
	public Connection getConn()
	{
		try {
			return DriverManager.getConnection(url, null, null);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
	}
	
	public static void main(String []a )
	{
		DbUtil db=new DbUtil();
		
		Connection con=db.getConn();
		
		try {
			 /*
			Statement st=con.createStatement();
			String username="Baidu";
			String password="1' or '1'='1";
			String sql="select * from user where username='"+username+"' and password='"+password+"'";
			System.out.println(sql);
			ResultSet rs=st.executeQuery(sql);
			while(rs.next()){
				System.out.println(	rs.getString("id"));
			} 
			
			String sql="insert into note(title,content,create_time,user_id) values(?,?,?,?)";
			//st.executeUpdate(sql, autoGeneratedKeys)
			PreparedStatement ps=con.prepareStatement(sql);
			ps.setString(1, " note_tit" );
			ps.setString(2, "content");
			ps.setDate(3, new java.sql.Date(new java.util.Date().getTime()) );
			ps.setInt(4,1);
			ps.executeUpdate();*/
			
			con.setAutoCommit(false);
			
			String sql="insert into note(title,content,create_time,user_id) values(?,?,?,?)";
			PreparedStatement ps=con.prepareStatement(sql);
			ps.setString(1, " note_tit" );
			ps.setString(2, "content");
			ps.setDate(3, new java.sql.Date(new java.util.Date().getTime()) );
			ps.setInt(4,1);
			ps.addBatch();
			
			ps.setString(1, " note_tit_2222" );
			ps.setString(2, "content_2222");
			ps.setDate(3, new java.sql.Date(new java.util.Date().getTime()) );
			ps.setInt(4,1);
			ps.addBatch();
			
			
			Savepoint sp1=con.setSavepoint("aaa");
			sql="insert into user(username,password,nick_name,address,icon)"
					+ " values(?,?,?,?,?)";
			PreparedStatement ps2=con.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);
			ps2.setString(1, " username" );
			ps2.setString(2, "password");
			ps2.setString(3, "nick_name");
			ps2.setString(4,"address");
			ps2.setString(5,"icon");
			ps2.addBatch();
			
			
			int aa[]=ps.executeBatch();
			for(int i=0;i<aa.length;i++)
			{
				System.out.println("result="+aa[i]);
			}
			
			
			try{
				ps2.executeUpdate();
				ResultSet key=ps2.getGeneratedKeys();
				if(key.next())
					System.out.println("key="+key.getInt(1));
			}catch(SQLException f){
				System.out.println("bbbb");
				con.rollback(sp1);
			}
			
			con.commit();
			System.out.println("aaaa");
			
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		
		try {
			con.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
	
	
	
	
}
